In [244]:
# Import der benötigten Bibliotheken
import numpy as np  # Für numerische Berechnungen und Arrays
import random       # Für die zufällige Generierung von Werten

In [245]:
# Funktion zur Erstellung einer zufälligen Disjunktiven Normalform (DNF)
def create_random_dnf(n, m):
    """
    Erstellt eine zufällige DNF mit n Variablen und m Monomen.
    
    Parameter:
    - n: Anzahl der Variablen
    - m: Anzahl der Monome
    
    Rückgabe:
    - Ein numpy-Array, das die DNF repräsentiert. 
      Jedes Monom ist ein Array mit Werten -1, 1 oder 0.
    """
    dnf = []  # Liste zur Speicherung der Monome
    for i in range(m):
        monome = []  # Ein einzelnes Monom
        for j in range(n):
            # Zufällige Auswahl von -1, 1 oder 0 für jedes Literal
            monome.append(random.choice([-1, 1, 0]))
        dnf.append(monome)  # Monom zur DNF hinzufügen
    return np.array(dnf)  # Rückgabe als numpy-Array

# Test: Erstelle eine zufällige DNF mit 10 Variablen und 5 Monomen
test_dnf = create_random_dnf(10, 5)
print(test_dnf)  # Ausgabe der generierten DNF


[[ 0 -1  1  0  0  0  0  1 -1  1]
 [ 0  0  1  1  1 -1  1  0 -1 -1]
 [-1  0  0  1 -1  0 -1  1  0 -1]
 [-1  0  0 -1  0  0  0  0 -1  0]
 [-1 -1  1  0  0  1  1  0  1  1]]


In [250]:
# Signum-Funktion (sig), die die Werte eines Vektors auf -1 oder 1 setzt
def sig(x):
    """
    Wendet die Signum-Funktion auf jeden Wert eines Vektors an.
    
    Parameter:
    - x: Eingabevektor (numpy-Array)
    
    Rückgabe:
    - Ein numpy-Array mit Werten -1 oder 1.
    """
    ret = np.copy(x)  # Kopiere den Eingabevektor
    for i in range(np.shape(x)[0]):  # Iteriere über alle Elemente
        if x[i] >= 0:
            ret[i] = 1  # Setze positive Werte auf 1
        else:
            ret[i] = -1  # Setze negative Werte auf -1
    return ret.astype(np.int64)  # Rückgabe als Integer-Array

In [251]:
# Funktion zur Berechnung der Anzahl der verwendeten Literale in einem Monom
def get_used_literals(monome):
    """
    Zählt die Anzahl der nicht-null Werte in einem Monom.
    
    Parameter:
    - monome: Ein Array, das ein Monom repräsentiert
    
    Rückgabe:
    - Anzahl der verwendeten Literale (Werte ungleich 0).
    """
    literal_count = 0
    for elem in monome:
        if elem != 0:
            literal_count += 1  # Erhöhe den Zähler für jedes nicht-null Element
    return literal_count

In [ ]:
# Funktion zur Berechnung der Zwischenwerte z
def calculate_z(w, x):
    """
    Berechnet die Zwischenwerte z basierend auf den Gewichten w und den Eingaben x.
    
    Parameter:
    - w: Gewichtsmatrix (numpy-Array), die die DNF repräsentiert
    - x: Eingabevektor (numpy-Array)
    
    Rückgabe:
    - Ein numpy-Array mit den berechneten z-Werten.
    """
    # Berechnung der v-Werte (Anzahl der Literale - 0.5)
    v = np.empty(w.shape[0], dtype=np.float64)  # Initialisiere v
    for i in range(w.shape[0]):
        v[i] = get_used_literals(w[i]) - 0.5  # Subtrahiere 0.5 von der Anzahl der Literale
    print(f"v list: {v}")  # Debug-Ausgabe der v-Werte

    # Berechnung der z-Werte
    z = np.empty(w.shape[0], dtype=np.float64)  # Initialisiere z
    for j in range(w.shape[0]):
        z[j] = np.dot(w[j], x) - v[j]  # Skalarprodukt minus v[j]
    z = sig(z)  # Wende die Signum-Funktion auf z an
    print(f"z list: {z}")  # Debug-Ausgabe der z-Werte
    
    return z  # Rückgabe der z-Werte

# Test: Berechne z für die generierte DNF und einen Eingabevektor
z = calculate_z(test_dnf, np.array([1, -1, 1, -1, 1, -1, 1, 1, 1, 1]).astype(np.int64))

In [249]:
def calculate_y(z):
    W = np.ones_like(z, dtype=np.int64)
    V = -(z.size - 1)
    print(f"V: {V}")	
    y = np.matmul(W, z.T)
    print(f"y raw: {y}")
    y = y - V
    if y >= 0:
        y = 1
    else:
        y = -1
    print(f"y: {y}")
    return y
    
print(f"y: {calculate_y(z)}")

V: -4
y raw: -5
y: -1
y: -1
